Name:           ros-indigo-strands-perception-people
Version:        0.0.8
Release:        0%{?dist}
Summary:        ROS strands_perception_people package

Group:          Development/Libraries
License:        MIT
URL:            https://github.com/strands-project/strands_perception_people
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-indigo-bayes-people-tracker
Requires:       ros-indigo-bayes-people-tracker-logging
Requires:       ros-indigo-ground-plane-estimation
Requires:       ros-indigo-mdl-people-tracker
Requires:       ros-indigo-odometry-to-motion-matrix
Requires:       ros-indigo-perception-people-launch
Requires:       ros-indigo-upper-body-detector
Requires:       ros-indigo-visual-odometry
BuildRequires:  ros-indigo-catkin

%description
The strands_perception_people metapackage

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Thu Oct 30 2014 Christian Dondrup <cdondrup@lincoln.ac.uk> - 0.0.8-0
- Autogenerated by Bloom

* Wed Oct 29 2014 Christian Dondrup <cdondrup@lincoln.ac.uk> - 0.0.5-0
- Autogenerated by Bloom

* Wed Oct 29 2014 Christian Dondrup <cdondrup@lincoln.ac.uk> - 0.0.7-0
- Autogenerated by Bloom

